version: "3.2"
services:
  app:
    command: node server.js
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${PORT:-3000}
        target: 3000
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      JWT_ACCESS_EXPIRATION_MINUTES: ${JWT_ACCESS_EXPIRATION_MINUTES}
      JWT_REFRESH_EXPIRATION_DAYS: ${JWT_REFRESH_EXPIRATION_DAYS}
      MONGODB_URL: ${MONGODB_URL}